name: EnhanceBridge
main: dev.yourorg.enhancebridge.EnhanceBridge
version: 1.0.0
api-version: 1.17
commands:
  enhancebridge:
    description: Skript → MMOItems 강화 브릿지 명령어
    usage: /enhancebridge enhance <스탯> <값>
